const recipes = [
    {
      title: "Pancakes",
      cookingTime: 30,
      image: './images/Pancakes.jpg',
      backgroundPosition: "-32.963px -5.14px",
      backgroundSize: "117.345% 78.7%",
    },
    {
      title : "Scrambled Eggs",
      cookingTime:10,
      image : './images/Scrambled-eggs.jpg',
      backgroundPosition: "-9.99px -3.754px",
      backgroundSize: "131.922% 77.727%",
    },
    {
      title : "Spaghetti Bolognese",
      cookingTime:45,
      image : './images/Spaghetti-bolognese.jpg',
      backgroundPosition: "50%",
      backgroundSize: "cover",
    },
    {
        title : "Caesar Salad",
        cookingTime:20,
        image : './images/Caesar-salad.jpg',
        backgroundPosition: "-22.697px 0px",
        backgroundSize: "121.766% 78.636%",
    },
    {
        title : "Vegetable Stir Fry",
        cookingTime:30,
        image : './images/Vegetable-stir-fry.jpg',
        backgroundPosition: "-2.717px -2.48px",
        backgroundSize: "102.144% 148.855%",
    },
    {
        title : "Grilled Cheese Sandwich",
        cookingTime:15,
        image : './images/Grilled-cheese-sando.jpg',
        backgroundPosition: "50%",
        backgroundSize: "cover",
    },
    {
        title : "Tomato Soup",
        cookingTime:45,
        image : './images/Tomato-soup.jpg',
        backgroundPosition: "0px -62.14px",
        backgroundSize: "100% 141.724%",
    },
    {
        title : "Chicken Curry",
        cookingTime:45,
        image : './images/Chicken-curry.jpg',
        backgroundPosition: "0px -26.691px",
        backgroundSize: "100% 125%",
    },
    {
        title : "French Toast",
        cookingTime:30,
        image : './images/French-toast.jpg',
        backgroundPosition: "0px -9.821px",
        backgroundSize: "100% 100%",
    },
    {
        title : "Beef Tacos",
        cookingTime:45,
        image : './images/Beef-tacos.jpg',
        backgroundPosition: "-8.132px -3.905px",
        backgroundSize: "105% 79.048%",
    },
    {
        title : "Mashed Potatoes",
        cookingTime:30,
        image : './images/Mashed-potatoes.jpg',
        backgroundPosition: "-27.846px 0px",
        backgroundSize: "115.303% 87.273%",
    },
    {
        title : "Chicken Alfredo",
        cookingTime:45,
        image : './images/Chicken-alfredo.jpg',
        backgroundPosition: "0.184px -87.864px",
        backgroundSize: "100% 150%",
    },
    {
        title : "Apple Pie",
        cookingTime:60,
        image : './images/Apple-pie.jpg',
        backgroundPosition: "-0.41px -79.4px",
        backgroundSize: "100% 150%",
    },
    {
        title : "Vegetable Soup",
        cookingTime:45,
        image : './images/Vegetable-soup.jpg',
        backgroundPosition: "0.758px -12.132px",
        backgroundSize: "100% 100%",
    },
    {
        title : "Chocolate Cake",
        cookingTime:60,
        image : './images/Chocolate-cake.jpg',
        backgroundPosition: "-17.188px -2.364px",
        backgroundSize: "130.994% 76.95%",
    },
  ];

  export default recipes;
  